server:
  port: 8082

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/resourcify-realm

logging:
  level:
    org:
      springframework:
        security: DEBUG
