server:
  port: 8082
  error:
    include-message: always

spring:
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: resource_db
      host: localhost
      port: 27017
      auto-index-creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000/realms/resourcify

logging:
  level:
    org:
      springframework:
        security: DEBUG

feign:
  name: user-client
  url: "http://localhost:8084"
