server:
  port: ${PORT:8082}
  error:
    include-message: always
keycloak:
  url: '${KEYCLOAK_URL:http://localhost:9000}'
  realm: "${KEYCLOAK_REALM:resourcify}"

spring:
  devtools:
    livereload:
      port: 38082
  data:
    mongodb:
      authentication-database: admin
      username: root
      password: root
      database: resource_db
      host: '${MONGO_HOST:localhost}'
      port: '${MONGO_PORT:27017}'
      auto-index-creation: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: '${keycloak.url}/realms/${keycloak.realm}'

logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot:
          autoconfigure: INFO # for dev tools logs

feign:
  name: user-client
  url: "${USER_SERVICE_URL:http://localhost:8084}"
