version: "3.8"
services:


  ################## RESOURCE-RESERVATION ##################

  #  resource-reservation-mongo:
  #    image: mongo
  #    ports:
  #      - "27017:27017"
  #    environmentProd:
  #      - MONGO_INITDB_ROOT_USERNAME=root
  #      - MONGO_INITDB_ROOT_PASSWORD=root
  #      - MONGO_INITDB_DATABASE=resource_db
  #    volumes:
  #      - data:/data

  ################## KEYCLOAK ##################
  keycloak-postgres:
    image: postgres
    volumes:
      - keycloak_postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak_postgres_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "6543:5432"

  keycloak:
    image: docker.io/bitnami/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_CREATE_ADMIN_USER: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak_postgres_db
      KEYCLOAK_DATABASE_USER: root
      KEYCLOAK_DATABASE_PASSWORD: root
      KEYCLOAK_IMPORT: /opt/bitnami/keycloak/data/import/realm-export.json
    volumes:
      - ./keycloak/realms:/opt/bitnami/keycloak/data/import
    depends_on:
      - keycloak-postgres
    entrypoint: '/opt/bitnami/keycloak/bin/kc.sh start-dev --import-realm'

    ################## USER-SERVICE ##################
  user-service:
    build: ./user-service
    ports:
      - '8084:8084'
    env_file:
      - ./user-service/.env
    environment:
      PORT: 8084
    depends_on:
      - keycloak

  ################## API-GATEWAY ##################
  api-gateway:
    build: ./api-gateway
    ports:
      - '8083:8083'
    env_file:
      - ./api-gateway/.env
    environment:
      PORT: 8083
    depends_on:
      - user-service

  frontend:
    build: ./frontend-angular
    command: 'sh -c "npm run start-docker"'
    working_dir: /home/node/app
    ports:
      - '4200:4200'
    volumes:
      - ./frontend-angular/:/home/node/app
      - node_modules:/home/node/app/node_modules
    depends_on:
      - 'keycloak'

volumes:
  data:
  keycloak_postgres_db:
  node_modules:
