server:
  port: ${PORT:8083}

logging:
  level:
    org:
      springframework:
        security: DEBUG
      boot:
        autoconfigure: INFO # for dev tools logs

spring:
  config:
    import: classpath:gateway.yml
