server:
  port: 8083

spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: http://localhost:4200
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - UPDATE
              - DELETE
      routes:
        - id: resources
          uri: http://localhost:8082
          predicates:
            Path=/messages/**
        - id: users
          uri: http://localhost:8084
          predicates:
            Path=/users/**

logging:
  level:
    org:
      springframework:
        security: DEBUG
