server:
  port: ${PORT:8083}

logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE
        security: DEBUG
      boot:
        autoconfigure: INFO # for dev tools logs

spring:
  devtools:
    livereload:
      port: 38083
  config:
    import: classpath:gateway.yml
