spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - UPDATE
              - DELETE
      routes:
        - id: resources
          uri: "${RESOURCES_URI:http://localhost:8082}"
          predicates:
            Path=/resources/**
        - id: users
          uri: "${USERS_URI:http://localhost:8084}"
          predicates:
            Path=/users/**
        - id: notification-service
          uri: "${NOTIFICATION_SERVICE:http://localhost:8000}"
          predicates:
            Path=/ws/**
