spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:4200, http://ll:4200"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
              - UPDATE
              - DELETE
      routes:
        - id: resources
          uri: http://localhost:8082
          predicates:
            Path=/resources/**
        - id: users
          uri: http://localhost:8084
          predicates:
            Path=/users/**
