version: "3"
services:
  rabbitmq:
    image: rabbitmq:3.8-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672" # default rabbitmq port
      - "15672:15672" # UI port
      - "15674:15674" # RabbitMQ STOMP (WebSocket) port
      - "61613:61613" # STOMP port
    volumes:
      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
