server:
  port: ${PORT:8084}
  error:
    include-message: always

keycloak:
  url: '${KEYCLOAK_URL:http://keycloak:8080}'
  realm: "${KEYCLOAK_REALM:resourcify}"
  admin:
    username: "${KEYCLOAK_ADMIN_USERNAME:admin}"
    password: "${KEYCLOAK_ADMIN_PASSWORD:admin}"

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://keycloak:8080/realms/resourcify'

logging:
  level:
    org:
      springframework:
        security: DEBUG




