server:
  port: ${PORT:8084}
  error:
    include-message: always

keycloak:
  url: '${KEYCLOAK_URL:http://localhost:9000}'
  realm: "${KEYCLOAK_REALM:resourcify}"
  admin:
    username: "${KEYCLOAK_ADMIN_USERNAME:admin}"
    password: "${KEYCLOAK_ADMIN_PASSWORD:admin}"

spring:
  devtools:
    livereload:
      port: 38084
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: '${keycloak.url}/realms/${keycloak.realm}'
logging:
  level:
    org:
      springframework:
        security: DEBUG
        boot:
          autoconfigure: INFO # for dev tools logs
